# -*- coding: utf-8 -*-
"""buoi4_btvn8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZJ9IroDbWIZ1wr4NMD5rfMSv6T13KiJ
"""

# Khởi tạo biến
player1_name = "Player 1"
player2_name = "Player 2"

while True:
    # Nhập số nguyên dương n và k
    n = int(input("n = "))

    k = int(input("k = "))

    # Kiểm tra điều kiện
    if n <= k:
        print("n > k")
        continue

    # Khởi tạo biến
    round_number = 1
    player1_turn = True
    player1_score = 0
    player2_score = 0
    player1_turn_violation = 0
    player2_turn_violation = 0

    # Vòng lặp round
    while True:
        # Xác định lượt chơi
        if player1_turn:
            player_name = player1_name
            player_score = player1_score
            turn_violation = player1_turn_violation
        else:
            player_name = player2_name
            player_score = player2_score
            turn_violation = player2_turn_violation

        # Yêu cầu nhập số nguyên dương trong đoạn [1, min(n,k)]
        print(f"{player_name} your turn")
        number = int(input("enter 1 num in range [1, min(n,k)]: "))

        # Kiểm tra điều kiện nhập
        if number < 1 or number > min(n, k):
            print("invalid")
            turn_violation += 1
            continue

        # Cập nhật giá trị
        if player1_turn:
            n -= number
            player1_turn = False
        else:
            n -= number
            player1_turn = True

        # Xem ai thắng round
        if n <= 0:
            if player1_turn:
                player1_score += 1
            else:
                player2_score += 1
            break

        # Xem ai muốn tiếp tục
        print(f"{player_name} want to continue ? (YES/NO)")
        continue_game = input().upper()
        while (continue_game != "YES" and continue_game != "NO"):
            continue_game = input("enter again ").upper()
        if continue_game == "NO":
            exit()

        # Tăng số vòng
        round_number += 1

    # Thống kê game
    winner = None
    win_rounds = []
    if player1_score > player2_score:
        winner = player1_name
        win_rounds = [i for i in range(
            1, round_number + 1) if player1_score == round_number - i]
    elif player2_score > player1_score:
        winner = player2_name
        win_rounds = [i for i in range(
            1, round_number + 1) if player2_score == round_number - i]

    # Xem ai phạm luật nhiều hơn
    elif player1_score == player2_score and player1_turn_violation > player2_turn_violation:
        winner = player2_name
    elif player1_score == player2_score and player2_turn_violation > player1_turn_violation:
        winner = player1_name
    elif player2_score == player1_score and player2_turn_violation == player1_turn_violation:
        winner = None
        win_rounds = []

    # Xem ai thắng chung cuộc
    if winner is not None:
        print(f"Player {winner} final win with {player1_score} win rounds ")
        print(f"Rounds {winner} win is: {win_rounds}")
    else:
        print("Draw")
