# -*- coding: utf-8 -*-
"""buoi4_btvn7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZJ9IroDbWIZ1wr4NMD5rfMSv6T13KiJ
"""

from IPython.utils.text import string
def split_list(list_input, n):
  size_sub_list = len(list_input) // n

  list_result = [[] for _ in range(n)]

  for i, item in enumerate(list_input):
    list_result[i % n].append(item)

  return list_result

list_input = list(map(str,input().split(" ")))
n = int(input())

list_result = split_list(list_input, n)

print(list_result)