# -*- coding: utf-8 -*-
"""buoi4_btvn6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZJ9IroDbWIZ1wr4NMD5rfMSv6T13KiJ
"""

list_input = list(map(int, input().split(" ")))

list_unique = set(list_input)
list_result = []
for value in list_unique:
    list_sub = []
    for item in list_input:
        if item == value:
            list_sub.append(item)
    list_result.append(list_sub)

print(list_result)
