# -*- coding: utf-8 -*-
"""buoi4_btvn2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZJ9IroDbWIZ1wr4NMD5rfMSv6T13KiJ
"""

def count_favorite_numbers(number_of_numbers, list_of_numbers):
    number_of_favorite_numbers = 0
    favorite_numbers = []
    for number in list_of_numbers:
        if number % 10 in [1, 3, 5, 7, 9]:
            number_of_favorite_numbers += 1
            favorite_numbers.append(number)

    print(number_of_favorite_numbers)
    print(" ".join(map(str, favorite_numbers)))


number_of_numbers = int(input())
list_of_numbers = list(map(int, input().split(" ")))
count_favorite_numbers(number_of_numbers, list_of_numbers)