# -*- coding: utf-8 -*-
"""buoi4_btvn3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mZJ9IroDbWIZ1wr4NMD5rfMSv6T13KiJ
"""

import re

def sum_numbers(string):
    numbers = []
    for match in re.findall(r"\d+|\-\d+", string):
        numbers.append(int(match))
    return sum(numbers)

str = input()
print(sum_numbers(str))